# Use official Node.js image
FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Set environment variable for port
ENV PORT=8080

# Expose the application's port
EXPOSE 8080

# Start the application, accepting environment variables
CMD ["npm", "start"]